title: Neurodivergent-friendly Workspace Manifesto
description: >
  Neurodivergent people often struggle within a neurotypical working environment.
  This manifesto aims to contribute to a more inclusive neurodivergent future.
  
  Licensed under <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>
baseurl: "/neurodivergent-workspace-manifesto/"
github_username: sourcefranke

remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
minima:
  skin: auto
